<map version="1.0.1">
<node TEXT="my title">
<node TEXT="1: Overview of A/B Testing">
<node TEXT="3. Intro to A/B Testing  "></node>
<node TEXT="5. Quiz: More A/B Testing Possibilities"></node>
<node TEXT="6. Other Techniques"></node>
<node TEXT="7. History of A/B Testing"></node>
<node TEXT="8. Overview of Business Example"></node>
<node TEXT="9. Metric Choice"></node>
<node TEXT="10. Estimating Click-Through-Probability"></node>
<node TEXT="11. Quiz: Repeating the Experiment"></node>
<node TEXT="12. Which Distribution?"></node>
<node TEXT="13. Quiz: Binomial Distribution"></node>
<node TEXT="14. Confidence Intervals "></node>
<node TEXT="15. Quiz: Calculating a Confidence Interval"></node>
<node TEXT="16. Establishing Statistical Significance"></node>
<node TEXT="17. Quiz: Null and Alternative Hypothesis"></node>
<node TEXT="18. Comparing Two Samples"></node>
<node TEXT="19. Pooled Standard Error"></node>
<node TEXT="20. Practical, or Substantive, Significance"></node>
<node TEXT="21. Size vs. Power Trade-Off"></node>
<node TEXT="22. How Page Views Affect Sensitivity"></node>
<node TEXT="23. Quiz: Calculating Number of Pages Views Needed"></node>
<node TEXT="24. Quiz: How Does Number of Page Views Vary?"></node>
<node TEXT="25. Quiz: Calculating Results"></node>
<node TEXT="26. Quiz: Confidence Interval Case Breakdown"></node>
<node TEXT="27. Making Decisions about Uncertain Data"></node>
<node TEXT="28. Conclusion"></node>
<node TEXT="29. Quiz: Survey Says!"></node></node>
<node TEXT="2: Policy and Ethics for Experiments"></node>
<node TEXT="3: Choosing and Characterizing Metrics"></node>
<node TEXT="4: Designing an Experiment"></node>
<node TEXT="5: Analyzing Results"></node>
<node TEXT="6: Final Project"></node>
</node></map>
