# Appendix


## The Giants
"If I have seen further, it is by standing on the shoulders of giants" by Isaac Newton.

Hadley Wickham

Joe Cheng

Yihui Xie 


## The Talk

All Things R and RStudio
Q&A with J.J. Allaire, Hadley Wickham & Joe Cheng
Moderator: Joseph Rickert
https://www.rstudio.com/resources/videos/all-things-r-and-rstudio/


Finding and Telling Stories with R
by Andrew Flowers from FiveThirtyEight
https://www.rstudio.com/resources/videos/finding-and-telling-stories-with-r/

install.packages('fivethirtyeight')
library(fivethirtyeight)

1.Novelty
2.Outlier
3.Archetype
4.Trend
5.Debunking
6.Forecast


## The Walk

follow the master,work with the master and become the master 


## Learning resource


## Reference

### web 
www.r-bloggers.com

www.rstudio.com

www.r-project.org

www.wikipedia.org

https://www.youtube.com/user/thenewboston/videos

https://www.youtube.com/user/sentdex/videos




### book
1.The Lady Tasting Tea by David Salsburg

2.The Art of R Programming by Norman Matloff 

3.R for Data Science by Hadley Wickham and Garrett Grolemund

4.Introduction to Statistical Learning(ISLR) by Gareth James,Daniela Witten and Trevor Hastie Robert Tibshirani

